title: Kai Ma # your name (or website title) here
logo: "/images/headshot_zoomed_square.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <a href="mailto:k78ma@uwaterloo.ca">Email</a> | <a href="https://www.linkedin.com/in/k78ma/">LinkedIn</a> | <a href="https://github.com/k78ma">GitHub</a>
  <br><br>
  Mechatronics Engineering @ UWaterloo.

  <br><br>
  Iâ€™m mainly interested in <b>AI/ML/DL</b>, especially in terms of their applications to <b>robotics</b> and autonomous systems. 
  Specific interests include:  <ul>
    <li>Perception (computer vision, deep learning)</li>
    <li>Motion planning & control</li>
    <li>Reinforcement learning & Simulation</li>
  </ul>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
