title: Kai Ma # your name (or website title) here
logo: "/images/headshot_zoomed_square.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Hi! I’m Kai, an undergraduate Mechatronics Engineering student at the University of Waterloo.

  <br><br>
  I’m mainly interested in AI/ML/DL, especially in terms of their applications to robotics and autonomous systems. Specific interests include perception (computer vision), motion planning (reinforcement learning, search/planning algorithms), control, and SLAM.
  Currently working at the Vision and Image Processing Group (UWaterloo) on deep learning for robotic arms.
  Past work: AI-assisted medical imaging (COVID-19 Diagnosis)
  <br><br>
  <a href="https://www.linkedin.com/in/k78ma/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
